name: Deploy to prod on manual trigger

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Nodejs
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install dependencies
        run: yarn

      - name: Deploy
        run: yarn deploy
        env:
          MARKET_STACK_ACCESS_KEY: ${{ secrets.MARKET_STACK_ACCESS_KEY }}
          BOT_CHAT_ID: ${{ secrets.BOT_CHAT_ID }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}